on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests

    env:
      CARGO_COMPONENT_VERSION: "0.20.0"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run `cargo test`
        run: cargo test

  rustfmt:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run `cargo fmt`
        run: cargo fmt --all -- --check
